# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/facial.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/facial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/facial.proto\x12\x06\x66\x61\x63ial\"\x1e\n\nFacialMesh\x12\x10\n\x08vertices\x18\x01 \x03(\x02\"2\n\x0cMeshResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\ngcode_path\x18\x02 \x01(\t2K\n\rFacialService\x12:\n\x0eSendFacialMesh\x12\x12.facial.FacialMesh\x1a\x14.facial.MeshResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.facial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACIALMESH']._serialized_start=30
  _globals['_FACIALMESH']._serialized_end=60
  _globals['_MESHRESPONSE']._serialized_start=62
  _globals['_MESHRESPONSE']._serialized_end=112
  _globals['_FACIALSERVICE']._serialized_start=114
  _globals['_FACIALSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
